name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/senpro-ssh-2
            echo "Cek folder project";
            [ ! -d "/home/seniorproject-rabu/senpro/463606/modul101/senpro-github-action/" && 
              {
                echo "Repository belum di-clone. Clonning...";
                mkdir -p ~/senpro/463606/modul101;
                cd ~/senpro/463606/modul101;
                git clone https://github.com/novaldypratama/senpro-github-action.git;
                cd ~/senpro/463606/modul101/senpro-github-action;
                echo "Install Package dan Build Project";
                npm install;
                npm run build;
              } ||
              {
                echo "Repository sudah ada. Building...";
                cd ~/senpro/463606/modul/senpro-github-action;
                git restore.;
                git pull origin main;
                echo "Install Package dan Build Project";
                npm install;
                npm run build;
              }
            ]
